# Generated by Django 4.0.3 on 2022-05-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='blank-article-picture.png', upload_to='images'),
        ),
    ]
